name: Detekt Report
on: [ pull_request ]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: detekt
        uses: DominuS-RU/Detekt-Action@master
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: ./config/detekt.yml # Change config path
        continue-on-error: true
