name: Detekt Report
on: [ pull_request ]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run detekt
        run: ./gradlew detekt
        continue-on-error: true

      - name: Display detekt report
        uses: danielhs1/comment-on-pr@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ./build/reports/detekt/detekt.md
