name: Detekt Report
on: [ pull_request ]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: detekt
        uses: alaegin/Detekt-Action@v1.23.6
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: ./config/detekt.yml # Change config path
          reviewdog_reporter: github-pr-review
        continue-on-error: true

      - name: All now
        run: ls -a

      - name: Publish Checkstyle report
        uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() || success() }}
        with:
          reports: ./detekt_report.xml
