name: Detekt Report
on: [ pull_request ]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run detekt
        run: ./gradlew detekt
        continue-on-error: true

      - uses: zattoo/output@v1
        name: Display results
        with:
          token: ${{github.token}}
          sources: './build/reports/detekt/'
