name: Detekt Report
on: [ pull_request ]

jobs:
  detekt:
    name: Check Code Quality
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run Detekt and generic result
        uses: alaegin/Detekt-Action@v1.23.6
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: ./config/detekt.yml
          reviewdog_reporter: github-pr-review
