name: Main Actions

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Static analyze
        run: ./gradlew detekt

      - name: Build source code
        run: ./gradlew build -x test

      - name: Display test results for library 'graphs-lab'
        run: python3 ./scripts/test-result-printer.py --dir ./graphs-lab/build/test-results/test --all-failures
