name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Build and test
        run: ./gradlew test
        continue-on-error: true

      - name: Run Coverage
        run: ./gradlew jacocoTestReport

      - name: Display path
        run: |
          ls -a ./graphs-lab/
          echo "============="
          ls -a ./graphs-lab/build
          echo "============="
          ls -a ./graphs-lab/build/reports
          echo "============="
          ls -a ./graphs-lab/build/reports/jacoco

      - name: Add coverage to PR
        uses: Andreea-Marcu/jacoco-report@v1.3.3
        with:
          paths: ./graphs-lab/build/reports/jacoco/info.xml
          token: ${{ secrets.GITHUB_TOKEN }}
