name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Build and test
        run: ./gradlew test
        continue-on-error: true

      - name: Run Coverage
        run: ./gradlew jacocoTestReport

      - name: Display path
        run: |
          ls -a ./graphs-lab/
          echo "============="
          ls -a ./graphs-lab/build
          echo "============="
          ls -a ./graphs-lab/build/reports
          echo "============="
          ls -a ./graphs-lab/build/reports/jacoco

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        id: jacoco
        with:
          paths: ./graphs-lab/build/reports/jacoco/info.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
